### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by DeamLake** [FoRTE-Research/UnTracer-AFL#9]
when I run 
untracer-afl -i in -o out -- ./size
It tells me that
**segmentation fault**
how can I fix it?
thx

**Comment by DeamLake** [comment]
size was from binutils
I make it by untracer-clang

**Comment by stevenagy** [comment]
More than likely this is due to the binary being compiled with untracer-clang as PIE instead of the required **non-PIE**. You can usually fix this by editing the `buildall.sh` in FoRTE-FuzzBench to add `-no-pie` to `passToAs`, e.g.:
```
compiler="/path/to/untracer-clang"
compilerXX="/path/to/untracer-clang++"
passToAS="-no-pie"
```
I'll add a couple of checks to UnTracer to try and detect when this happens.

**Comment by stevenagy** [comment]
Closing as it seems to be resolved.
